# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: 
  workflow_dispatch:
  #push:
   # branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Java Unit Test and Analysis with SonarCloud
  # You may pin to the exact commit or the version.
  # uses: bcgov-nr/action-test-and-analyse-java@e70f9d6f082697b6318f233edfb21edf46a6c73b
  uses: bcgov-nr/action-test-and-analyse-java@v1.0.0
  with:
    # Commands to run tests, start with '|' for multi-line
    commands: 
    # App/package directory
    dir: 
    # Java version, defaults to 17 (LTS)
    java-version: 
    # Java package manager cache, defaults to maven
    java-cache: # optional, default is maven
    # Java distribution, defaults to temurin
    java-distribution: # optional, default is temurin
    # SonarCloud command line arguments
    sonar_args: # optional, default is -Dsonar.organization=bcgov-sonarcloud
-Dsonar.projectKey=bcgov_${{ github.repository }}

    # Sonar token, provide unpopulated token for pre-setup (will skip)
    sonar_token: # optional
    # Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)
    triggers: # optional
    # Branch to diff against
    diff_branch: # optional, default is ${{ github.event.repository.default_branch }}
    # Non-default repository to clone (used for testing this action)
    repository: # optional, default is ${{ github.repository }}
    # Non-default branch to clone (used for testing this action)
    branch: # optional, default is 
    # Events (array) to use with triggers; e.g. ("pull_request" "push" "workflow_dispatch")
    triggers_event: # optional, default is ('pull_request')
              
    
